import trial_updater
import get_company_data
import phARKma_utils
import get_relationships
import get_trials
import trial_updater
import airtable_utils
import get_condition_category
import get_arkg_tickers
import get_details
import get_commercialized_drugs




trial_updater.check_trial_deprecation_status(True)